import { describe, expect, it, vi } from "vitest";
import { OpenAIEngine, __testUtils } from "../src/engines/openaiEngine.js";

describe("OpenAIEngine", () => {
  it("builds a response request and parses JSON output", async () => {
    const create = vi.fn(async () => ({
      output_text: '{"command":"printf \\"123\\\\n\\"","explanation":"Print a known value."}'
    }));
    const engine = new OpenAIEngine({
      apiKey: "test-key",
      model: "gpt-test",
      client: {
        responses: {
          create
        }
      }
    });

    const result = await engine.generateCommand({
      problem: "print 123",
      attempts: [
        {
          command: "printf '0\\n'",
          passed: false,
          failureReason: "wrong output"
        }
      ],
      workdir: "/tmp/workdir",
      workerId: "worker-2",
      strategy: "awk-first"
    });

    expect(result).toEqual({
      command: 'printf "123\\n"',
      explanation: "Print a known value."
    });
    expect(create).toHaveBeenCalledTimes(1);
    expect(create.mock.calls[0][0]).toMatchObject({
      model: "gpt-test"
    });
    expect(JSON.stringify(create.mock.calls[0][0].input)).toContain("worker-2");
    expect(JSON.stringify(create.mock.calls[0][0].input)).toContain("wrong output");
  });

  it("fails with a clear message when the API key is missing", async () => {
    const engine = new OpenAIEngine({
      apiKey: ""
    });

    await expect(
      engine.generateCommand({
        problem: "print 123",
        attempts: [],
        workdir: "/tmp/workdir"
      })
    ).rejects.toThrow("OPENAI_API_KEY is not set. Set it and retry, or use --engine mock.");
  });
});

describe("openaiEngine test utils", () => {
  it("extracts JSON from fenced responses", () => {
    const { parseEngineResponse } = __testUtils();
    expect(parseEngineResponse('```json\n{"command":"printf \\"ok\\\\n\\""}\n```')).toEqual({
      command: 'printf "ok\\n"',
      explanation: "Generated by OpenAI API."
    });
  });
});
