import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { commandExists } from "../util/exec.js";

const execFileAsync = promisify(execFile);

function buildPrompt(context) {
  return [
    "Return only a shell command.",
    "Do not include markdown fences or explanation.",
    "Do not execute anything yourself.",
    "Problem:",
    context.problem,
    context.attempts.length > 0 ? `Previous attempts: ${JSON.stringify(context.attempts)}` : ""
  ]
    .filter(Boolean)
    .join("\n");
}

export class CursorCliEngine {
  name = "cursor";

  async generateCommand(context) {
    const exists = await commandExists("cursor");
    if (!exists) {
      throw new Error("The 'cursor' CLI was not found in PATH. Install it or use --engine mock.");
    }

    const prompt = buildPrompt(context);
    const result = await execFileAsync("cursor", ["agent", prompt], {
      cwd: context.workdir,
      env: {
        PATH: process.env.PATH ?? "",
        HOME: process.env.HOME ?? ""
      },
      timeout: 15_000
    });

    const command = result.stdout.trim();
    if (!command) {
      throw new Error("The 'cursor' CLI returned an empty command.");
    }

    return {
      command,
      explanation: "Generated by Cursor CLI."
    };
  }
}
