function buildSystemPrompt() {
  return [
    "You generate a single shell command for a shell-gei problem.",
    "Return JSON only.",
    'Use shape {"command":"...","explanation":"..."}.',
    "Do not include markdown fences.",
    "Do not execute commands.",
    "Prefer a shell-gei style one-liner.",
    "Favor natural stdin/stdout flow with standard Unix tools.",
    "Avoid redundant cat, duplicated passes, temporary files, or embedded scripts.",
    "Prefer a single safe one-liner that works in the provided workdir."
  ].join(" ");
}

function buildUserPrompt(context) {
  const workerTask = context.workerTask ?? null;
  const attemptSummary =
    context.attempts.length > 0
      ? JSON.stringify(
          context.attempts.map((attempt) => ({
            command: attempt.command,
            reason: attempt.failureReason ?? "",
            passed: attempt.passed ?? false,
            durationMs: attempt.durationMs ?? null
          }))
        )
      : "[]";

  return [
    `Problem: ${context.problem}`,
    `Working directory: ${context.workdir}`,
    context.workerId ? `Worker: ${context.workerId}` : "",
    context.strategy ? `Strategy: ${context.strategy}` : "",
    workerTask?.strategyProfile?.name ? `Worker role: ${workerTask.strategyProfile.name}` : "",
    workerTask?.strategyProfile?.focus ? `Role focus: ${workerTask.strategyProfile.focus}` : "",
    workerTask?.strategyProfile?.retryHint
      ? `Retry hint: ${workerTask.strategyProfile.retryHint}`
      : "",
    workerTask?.strategyProfile?.rubricFocus?.length
      ? `Shellgei rubric focus: ${workerTask.strategyProfile.rubricFocus.join(", ")}`
      : "",
    workerTask?.assignedVariant?.label ? `Assigned variant: ${workerTask.assignedVariant.label}` : "",
    workerTask?.assignedVariant?.approach
      ? `Variant approach: ${workerTask.assignedVariant.approach}`
      : "",
    workerTask?.assignedVariant?.toolBias?.length
      ? `Preferred tool bias: ${workerTask.assignedVariant.toolBias.join(", ")}`
      : "",
    workerTask?.assignedVariant?.intent
      ? `Variant intent: ${workerTask.assignedVariant.intent}`
      : "",
    workerTask?.assignedVariant?.constraints?.length
      ? `Variant constraints: ${workerTask.assignedVariant.constraints.join(", ")}`
      : "",
    workerTask?.assignedVariant?.avoid?.length
      ? `Avoid while exploring: ${workerTask.assignedVariant.avoid.join(", ")}`
      : "",
    workerTask?.assignedVariant?.explorationHint
      ? `Exploration hint: ${workerTask.assignedVariant.explorationHint}`
      : "",
    workerTask?.assignedVariant?.toolSuggestions?.length
      ? `Variant tool suggestions: ${JSON.stringify(workerTask.assignedVariant.toolSuggestions)}`
      : "",
    workerTask?.assignedVariant
      ? "Use assigned variant as a soft exploration axis, not a rigid first step."
      : "",
    workerTask?.assignedVariant?.toolSuggestions?.length
      ? "Use suggestedTools as optional starting points, but choose any safer or better tools if needed."
      : "",
    `Retry budget: ${workerTask?.maxAttempts ?? 1}`,
    `Previous attempts: ${attemptSummary}`
  ]
    .filter(Boolean)
    .join("\n");
}

function stripCodeFence(raw) {
  return raw
    .trim()
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/\s*```$/, "");
}

function parseEngineResponse(raw) {
  let parsed;

  try {
    parsed = JSON.parse(stripCodeFence(raw));
  } catch {
    throw new Error("The OpenAI engine returned non-JSON response.");
  }

  if (!parsed || typeof parsed.command !== "string" || !parsed.command.trim()) {
    throw new Error("The OpenAI engine returned JSON response without command.");
  }

  return {
    command: parsed.command.trim(),
    explanation:
      typeof parsed.explanation === "string" && parsed.explanation.trim()
        ? parsed.explanation.trim()
        : "Generated by OpenAI API."
  };
}

function isNonJsonResponseError(error) {
  return error instanceof Error && error.message === "The OpenAI engine returned non-JSON response.";
}

function extractResponseText(response) {
  if (typeof response?.output_text === "string" && response.output_text.trim()) {
    return response.output_text.trim();
  }

  const chunks = [];
  for (const item of response?.output ?? []) {
    for (const content of item?.content ?? []) {
      if (content?.type === "output_text" && typeof content.text === "string") {
        chunks.push(content.text);
      }
    }
  }

  const text = chunks.join("\n").trim();
  if (text.length > 0) {
    return text;
  }

  throw new Error("The OpenAI engine returned no text output.");
}

async function createDefaultClient(options) {
  let OpenAI;

  try {
    ({ default: OpenAI } = await import("openai"));
  } catch {
    throw new Error("The 'openai' package is not installed. Run 'npm install' and try again.");
  }

  return new OpenAI({
    apiKey: options.apiKey,
    baseURL: options.baseURL,
    timeout: options.timeoutMs,
    maxRetries: options.maxRetries
  });
}

function resolvePositiveInteger(value, fallback) {
  if (value == null || value === "") {
    return fallback;
  }

  const parsed = Number(value);
  if (!Number.isInteger(parsed) || parsed <= 0) {
    return fallback;
  }

  return parsed;
}

export class OpenAIEngine {
  name = "openai";

  constructor(options = {}) {
    this.model = options.model ?? process.env.OPENAI_MODEL ?? "gpt-5.4-mini";
    this.apiKey = options.apiKey ?? process.env.OPENAI_API_KEY ?? "";
    this.baseURL = options.baseURL ?? process.env.OPENAI_BASE_URL;
    this.timeoutMs = resolvePositiveInteger(options.timeoutMs, 10_000);
    this.maxRetries = resolvePositiveInteger(options.maxRetries, 2);
    this.client = options.client ?? null;
    this.clientFactory = options.clientFactory ?? createDefaultClient;
    this.clientPromise = null;
  }

  async generateCommand(context) {
    const client = await this.#getClient();
    let lastError;

    for (let attempt = 0; attempt <= this.maxRetries; attempt += 1) {
      try {
        const response = await client.responses.create({
          model: this.model,
          input: [
            {
              role: "system",
              content: [{ type: "input_text", text: buildSystemPrompt() }]
            },
            {
              role: "user",
              content: [{ type: "input_text", text: buildUserPrompt(context) }]
            }
          ]
        });

        return parseEngineResponse(extractResponseText(response));
      } catch (error) {
        if (!isNonJsonResponseError(error) || attempt >= this.maxRetries) {
          throw error;
        }

        lastError = error;
      }
    }

    throw lastError ?? new Error("The OpenAI engine returned non-JSON response.");
  }

  async #getClient() {
    if (this.client) {
      return this.client;
    }

    if (!this.apiKey) {
      throw new Error("OPENAI_API_KEY is not set. Set it and retry, or use --engine mock.");
    }

    this.clientPromise ??= this.clientFactory({
      apiKey: this.apiKey,
      baseURL: this.baseURL,
      timeoutMs: this.timeoutMs,
      maxRetries: this.maxRetries
    });
    this.client = await this.clientPromise;

    return this.client;
  }
}

export function __testUtils() {
  return {
    buildUserPrompt,
    extractResponseText,
    parseEngineResponse
  };
}
