function buildSystemPrompt() {
  return [
    "You generate a single shell command for a shell-gei problem.",
    "Return JSON only.",
    'Use the shape {"command":"...","explanation":"..."}.',
    "Do not include markdown fences.",
    "Do not execute commands.",
    "Prefer a single safe one-liner that works in the provided workdir."
  ].join(" ");
}

function buildUserPrompt(context) {
  return [
    `Problem: ${context.problem}`,
    `Working directory: ${context.workdir}`,
    context.workerId ? `Worker: ${context.workerId}` : "",
    context.strategy ? `Strategy: ${context.strategy}` : "",
    context.attempts.length > 0
      ? `Previous attempts: ${JSON.stringify(context.attempts.map((attempt) => ({ command: attempt.command, reason: attempt.failureReason ?? "", passed: attempt.passed ?? false })))}`
      : "Previous attempts: []"
  ]
    .filter(Boolean)
    .join("\n");
}

function stripCodeFence(text) {
  const trimmed = text.trim();
  const fenceMatch = trimmed.match(/^```(?:json)?\s*([\s\S]*?)\s*```$/i);
  return fenceMatch ? fenceMatch[1].trim() : trimmed;
}

function extractJsonObject(text) {
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start === -1 || end === -1 || end <= start) {
    return text;
  }

  return text.slice(start, end + 1);
}

function parseEngineResponse(text) {
  const normalized = extractJsonObject(stripCodeFence(text));
  let parsed;

  try {
    parsed = JSON.parse(normalized);
  } catch {
    throw new Error("The OpenAI engine returned a non-JSON response.");
  }

  if (typeof parsed?.command !== "string" || parsed.command.trim().length === 0) {
    throw new Error("The OpenAI engine returned JSON without a non-empty command.");
  }

  return {
    command: parsed.command.trim(),
    explanation:
      typeof parsed.explanation === "string" && parsed.explanation.trim().length > 0
        ? parsed.explanation.trim()
        : "Generated by OpenAI API."
  };
}

function extractResponseText(response) {
  if (typeof response?.output_text === "string" && response.output_text.trim().length > 0) {
    return response.output_text.trim();
  }

  if (Array.isArray(response?.output)) {
    const text = response.output
      .flatMap((item) => (Array.isArray(item?.content) ? item.content : []))
      .map((content) => {
        if (typeof content?.text === "string") {
          return content.text;
        }
        if (typeof content?.output_text === "string") {
          return content.output_text;
        }
        return "";
      })
      .filter(Boolean)
      .join("\n")
      .trim();

    if (text.length > 0) {
      return text;
    }
  }

  throw new Error("The OpenAI engine returned no text output.");
}

async function createDefaultClient(options) {
  let OpenAI;

  try {
    ({ default: OpenAI } = await import("openai"));
  } catch {
    throw new Error("The 'openai' package is not installed. Run 'npm install' and try again.");
  }

  return new OpenAI({
    apiKey: options.apiKey,
    baseURL: options.baseURL,
    timeout: options.timeoutMs,
    maxRetries: options.maxRetries
  });
}

function resolvePositiveInteger(value, fallback) {
  if (value == null || value === "") {
    return fallback;
  }

  const parsed = Number(value);
  if (!Number.isInteger(parsed) || parsed <= 0) {
    return fallback;
  }

  return parsed;
}

export class OpenAIEngine {
  name = "openai";

  constructor(options = {}) {
    this.model = options.model ?? process.env.OPENAI_MODEL ?? "gpt-5.4-mini";
    this.apiKey = options.apiKey ?? process.env.OPENAI_API_KEY ?? "";
    this.baseURL = options.baseURL ?? process.env.OPENAI_BASE_URL;
    this.timeoutMs = resolvePositiveInteger(options.timeoutMs ?? process.env.OPENAI_TIMEOUT_MS, 15_000);
    this.maxRetries = resolvePositiveInteger(options.maxRetries ?? process.env.OPENAI_MAX_RETRIES, 2);
    this.client = options.client ?? null;
    this.clientFactory = options.clientFactory ?? createDefaultClient;
    this.clientPromise = null;
  }

  async generateCommand(context) {
    const client = await this.#getClient();
    const response = await client.responses.create({
      model: this.model,
      input: [
        {
          role: "system",
          content: [
            {
              type: "input_text",
              text: buildSystemPrompt()
            }
          ]
        },
        {
          role: "user",
          content: [
            {
              type: "input_text",
              text: buildUserPrompt(context)
            }
          ]
        }
      ]
    });

    return parseEngineResponse(extractResponseText(response));
  }

  async #getClient() {
    if (this.client) {
      return this.client;
    }

    if (!this.apiKey) {
      throw new Error("OPENAI_API_KEY is not set. Set it and retry, or use --engine mock.");
    }

    this.clientPromise ??= this.clientFactory({
      apiKey: this.apiKey,
      baseURL: this.baseURL,
      timeoutMs: this.timeoutMs,
      maxRetries: this.maxRetries
    });

    this.client = await this.clientPromise;
    return this.client;
  }
}

export function __testUtils() {
  return {
    buildUserPrompt,
    extractResponseText,
    parseEngineResponse
  };
}
