import { execFile } from "node:child_process";
import { promisify } from "node:util";

import { commandExists } from "../../util/exec.js";

const execFileAsync = promisify(execFile);

function buildPrompt(context) {
  const workerTask = context.workerTask ?? null;

  return [
    "Return only the shell command.",
    "Do not include markdown fences or explanation.",
    "Do not execute anything yourself.",
    "Prefer a shell-gei style one-liner.",
    "Favor stdin/stdout flow with standard Unix tools.",
    workerTask?.strategyProfile?.rubricFocus?.length
      ? `Shellgei rubric focus: ${workerTask.strategyProfile.rubricFocus.join(", ")}`
      : "",
    workerTask?.assignedVariant?.label ? `Assigned variant: ${workerTask.assignedVariant.label}` : "",
    workerTask?.assignedVariant?.approach
      ? `Variant approach: ${workerTask.assignedVariant.approach}`
      : "",
    workerTask?.assignedVariant?.toolBias?.length
      ? `Preferred tool bias: ${workerTask.assignedVariant.toolBias.join(", ")}`
      : "",
    workerTask?.assignedVariant?.intent
      ? `Variant intent: ${workerTask.assignedVariant.intent}`
      : "",
    workerTask?.assignedVariant?.constraints?.length
      ? `Variant constraints: ${workerTask.assignedVariant.constraints.join(", ")}`
      : "",
    workerTask?.assignedVariant?.avoid?.length
      ? `Avoid while exploring: ${workerTask.assignedVariant.avoid.join(", ")}`
      : "",
    workerTask?.assignedVariant?.explorationHint
      ? `Exploration hint: ${workerTask.assignedVariant.explorationHint}`
      : "",
    workerTask?.assignedVariant?.toolSuggestions?.length
      ? `Variant tool suggestions: ${JSON.stringify(workerTask.assignedVariant.toolSuggestions)}`
      : "",
    workerTask?.assignedVariant
      ? "Use assigned variant as a soft exploration axis, not a rigid first step."
      : "",
    workerTask?.assignedVariant?.toolSuggestions?.length
      ? "Use suggestedTools as optional starting points, but choose any safer or better tools if needed."
      : "",
    "Problem:",
    context.problem,
    context.attempts.length > 0 ? `Previous attempts: ${JSON.stringify(context.attempts)}` : ""
  ]
    .filter(Boolean)
    .join("\n");
}

export class CodexCliEngine {
  name = "codex-cli";

  constructor(options = {}) {
    this.command = options.command ?? "codex";
    this.args = options.args ?? ["exec", "--json"];
  }

  async generateCommand(context) {
    if (!(await commandExists(this.command))) {
      throw new Error(`The '${this.command}' command is not installed or not in PATH.`);
    }

    const prompt = buildPrompt(context);
    const { stdout } = await execFileAsync(this.command, [...this.args, prompt], {
      cwd: context.workdir,
      env: process.env
    });

    const command = String(stdout ?? "").trim();
    if (!command) {
      throw new Error("The Codex CLI engine returned an empty command.");
    }

    return {
      command,
      explanation: "Generated by Codex CLI."
    };
  }
}
