function buildSystemPrompt() {
  return [
    "You generate a single shell command for a shell-gei problem.",
    "Return JSON only.",
    'Use shape {"command":"...","explanation":"..."}.',
    "Do not include markdown fences.",
    "Do not execute commands.",
    "Prefer a shell-gei style one-liner.",
    "Favor natural stdin/stdout flow with standard Unix tools.",
    "Avoid redundant cat, duplicated passes, temporary files, or embedded scripts.",
    "Prefer a single safe one-liner that works in the provided workdir."
  ].join(" ");
}

const STRICT_TOOL_SCHEMA_ERROR =
  "The OpenAI engine received a Tool schema incompatible with strict mode.";

function buildUserPrompt(context) {
  const workerTask = context.workerTask ?? null;
  const attemptSummary =
    context.attempts.length > 0
      ? JSON.stringify(
          context.attempts.map((attempt) => ({
            command: attempt.command,
            reason: attempt.failureReason ?? "",
            passed: attempt.passed ?? false,
            durationMs: attempt.durationMs ?? null
          }))
        )
      : "[]";

  return [
    `Problem: ${context.problem}`,
    `Working directory: ${context.workdir}`,
    context.workerId ? `Worker: ${context.workerId}` : "",
    context.strategy ? `Strategy: ${context.strategy}` : "",
    workerTask?.strategyProfile?.name ? `Worker role: ${workerTask.strategyProfile.name}` : "",
    workerTask?.strategyProfile?.focus ? `Role focus: ${workerTask.strategyProfile.focus}` : "",
    workerTask?.strategyProfile?.retryHint
      ? `Retry hint: ${workerTask.strategyProfile.retryHint}`
      : "",
    workerTask?.strategyProfile?.rubricFocus?.length
      ? `Shellgei rubric focus: ${workerTask.strategyProfile.rubricFocus.join(", ")}`
      : "",
    workerTask?.assignedVariant?.label ? `Assigned variant: ${workerTask.assignedVariant.label}` : "",
    workerTask?.assignedVariant?.approach
      ? `Variant approach: ${workerTask.assignedVariant.approach}`
      : "",
    workerTask?.assignedVariant?.toolBias?.length
      ? `Preferred tool bias: ${workerTask.assignedVariant.toolBias.join(", ")}`
      : "",
    workerTask?.assignedVariant?.intent
      ? `Variant intent: ${workerTask.assignedVariant.intent}`
      : "",
    workerTask?.assignedVariant?.constraints?.length
      ? `Variant constraints: ${workerTask.assignedVariant.constraints.join(", ")}`
      : "",
    workerTask?.assignedVariant?.avoid?.length
      ? `Avoid while exploring: ${workerTask.assignedVariant.avoid.join(", ")}`
      : "",
    workerTask?.assignedVariant?.explorationHint
      ? `Exploration hint: ${workerTask.assignedVariant.explorationHint}`
      : "",
    workerTask?.assignedVariant?.toolSuggestions?.length
      ? `Variant tool suggestions: ${JSON.stringify(workerTask.assignedVariant.toolSuggestions)}`
      : "",
    workerTask?.assignedVariant
      ? "Use assigned variant as a soft exploration axis, not a rigid first step."
      : "",
    workerTask?.assignedVariant?.toolSuggestions?.length
      ? "Use suggestedTools as optional starting points, but choose any safer or better tools if needed."
      : "",
    `Retry budget: ${workerTask?.maxAttempts ?? 1}`,
    `Previous attempts: ${attemptSummary}`
  ]
    .filter(Boolean)
    .join("\n");
}

function stripCodeFence(raw) {
  return raw
    .trim()
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/\s*```$/, "");
}

function parseEngineResponse(raw) {
  let parsed;

  try {
    parsed = JSON.parse(stripCodeFence(raw));
  } catch {
    throw new Error("The OpenAI engine returned non-JSON response.");
  }

  if (!parsed || typeof parsed.command !== "string" || !parsed.command.trim()) {
    throw new Error("The OpenAI engine returned JSON response without command.");
  }

  return {
    command: parsed.command.trim(),
    explanation:
      typeof parsed.explanation === "string" && parsed.explanation.trim()
        ? parsed.explanation.trim()
        : "Generated by OpenAI API."
  };
}

function parseToolCallArguments(raw) {
  let parsed;

  try {
    parsed = JSON.parse(raw);
  } catch {
    throw new Error("The OpenAI engine returned invalid Tool call arguments.");
  }

  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error("The OpenAI engine returned invalid Tool call arguments.");
  }

  return parsed;
}

function isNonEmptyString(value) {
  return typeof value === "string" && value.trim().length > 0;
}

function serializeToolResult(result) {
  let serialized;

  try {
    serialized = JSON.stringify(result);
  } catch {
    throw new Error("The OpenAI engine could not serialize a Tool result.");
  }

  if (typeof serialized !== "string") {
    throw new Error("The OpenAI engine could not serialize a Tool result.");
  }

  return serialized;
}

function isObjectSchema(schema) {
  return (
    schema?.type === "object" ||
    (Array.isArray(schema?.type) && schema.type.includes("object"))
  );
}

function assertOpenAIStrictSchema(rootSchema) {
  const visited = new Set();

  function visit(schema, isRoot = false) {
    if (!schema || typeof schema !== "object") {
      if (isRoot) {
        throw new Error(STRICT_TOOL_SCHEMA_ERROR);
      }
      return;
    }
    if (visited.has(schema)) {
      return;
    }
    visited.add(schema);
    if (Array.isArray(schema)) {
      if (isRoot) {
        throw new Error(STRICT_TOOL_SCHEMA_ERROR);
      }
      for (const item of schema) {
        visit(item);
      }
      return;
    }

    if (isRoot || isObjectSchema(schema) || Object.hasOwn(schema, "properties")) {
      const properties = schema.properties;
      const required = schema.required;
      const propertyNames =
        properties && typeof properties === "object" && !Array.isArray(properties)
          ? Object.keys(properties)
          : null;
      const requiredNames = Array.isArray(required) ? new Set(required) : null;

      if (
        (isRoot ? schema.type !== "object" : !isObjectSchema(schema)) ||
        propertyNames === null ||
        schema.additionalProperties !== false ||
        requiredNames === null ||
        requiredNames.size !== propertyNames.length ||
        !propertyNames.every((name) => requiredNames.has(name))
      ) {
        throw new Error(STRICT_TOOL_SCHEMA_ERROR);
      }
    }

    for (const schemaMap of [
      schema.properties,
      schema.$defs,
      schema.definitions,
      schema.dependentSchemas,
      schema.patternProperties
    ]) {
      if (schemaMap && typeof schemaMap === "object" && !Array.isArray(schemaMap)) {
        for (const childSchema of Object.values(schemaMap)) {
          visit(childSchema);
        }
      }
    }
    for (const childSchema of [
      schema.items,
      schema.prefixItems,
      schema.contains,
      schema.not,
      schema.if,
      schema.then,
      schema.else,
      schema.propertyNames,
      schema.anyOf,
      schema.oneOf,
      schema.allOf
    ]) {
      visit(childSchema);
    }
  }

  visit(rootSchema, true);
}

function isNonJsonResponseError(error) {
  return error instanceof Error && error.message === "The OpenAI engine returned non-JSON response.";
}

function extractOptionalResponseText(response) {
  if (typeof response?.output_text === "string" && response.output_text.trim()) {
    return response.output_text.trim();
  }

  const chunks = [];
  for (const item of response?.output ?? []) {
    for (const content of item?.content ?? []) {
      if (content?.type === "output_text" && typeof content.text === "string") {
        chunks.push(content.text);
      }
    }
  }

  const text = chunks.join("\n").trim();
  if (text.length > 0) {
    return text;
  }

  return "";
}

function extractResponseText(response) {
  const text = extractOptionalResponseText(response);
  if (text) {
    return text;
  }

  throw new Error("The OpenAI engine returned no text output.");
}

async function createDefaultClient(options) {
  let OpenAI;

  try {
    ({ default: OpenAI } = await import("openai"));
  } catch {
    throw new Error("The 'openai' package is not installed. Run 'npm install' and try again.");
  }

  return new OpenAI({
    apiKey: options.apiKey,
    baseURL: options.baseURL,
    timeout: options.timeoutMs,
    maxRetries: options.maxRetries
  });
}

function resolvePositiveInteger(value, fallback) {
  if (value == null || value === "") {
    return fallback;
  }

  const parsed = Number(value);
  if (!Number.isInteger(parsed) || parsed <= 0) {
    return fallback;
  }

  return parsed;
}

export class OpenAIEngine {
  name = "openai";
  capabilities = { toolCalling: true };

  constructor(options = {}) {
    this.model = options.model ?? process.env.OPENAI_MODEL ?? "gpt-5.4-mini";
    this.apiKey = options.apiKey ?? process.env.OPENAI_API_KEY ?? "";
    this.baseURL = options.baseURL ?? process.env.OPENAI_BASE_URL;
    this.timeoutMs = resolvePositiveInteger(options.timeoutMs, 10_000);
    this.maxRetries = resolvePositiveInteger(options.maxRetries, 2);
    this.client = options.client ?? null;
    this.clientFactory = options.clientFactory ?? createDefaultClient;
    this.clientPromise = null;
  }

  async generateCommand(context) {
    const client = await this.#getClient();
    let lastError;

    for (let attempt = 0; attempt <= this.maxRetries; attempt += 1) {
      try {
        const response = await client.responses.create({
          model: this.model,
          input: [
            {
              role: "system",
              content: [{ type: "input_text", text: buildSystemPrompt() }]
            },
            {
              role: "user",
              content: [{ type: "input_text", text: buildUserPrompt(context) }]
            }
          ]
        });

        return parseEngineResponse(extractResponseText(response));
      } catch (error) {
        if (!isNonJsonResponseError(error) || attempt >= this.maxRetries) {
          throw error;
        }

        lastError = error;
      }
    }

    throw lastError ?? new Error("The OpenAI engine returned non-JSON response.");
  }

  async generateTurn({ context, tools, continuation, toolResults = [] }) {
    const openaiTools = tools.map(({ name, description, parameters }) => {
      assertOpenAIStrictSchema(parameters);
      return {
        type: "function",
        name,
        description,
        parameters,
        strict: true
      };
    });
    const request = continuation
      ? {
          model: this.model,
          previous_response_id: continuation.responseId,
          input: toolResults.map(({ callId, result }) => ({
            type: "function_call_output",
            call_id: callId,
            output: serializeToolResult(result)
          })),
          tools: openaiTools
        }
      : {
          model: this.model,
          input: [
            {
              role: "system",
              content: [{ type: "input_text", text: buildSystemPrompt() }]
            },
            {
              role: "user",
              content: [{ type: "input_text", text: buildUserPrompt(context) }]
            }
          ],
          tools: openaiTools
        };
    const client = await this.#getClient();
    const response = await client.responses.create(request);

    if (response?.status != null && response.status !== "completed") {
      throw new Error("The OpenAI engine returned a non-completed response.");
    }

    const functionCalls = (response.output ?? []).filter(
      (item) => item?.type === "function_call"
    );

    if (
      functionCalls.some((call) => call.status != null && call.status !== "completed")
    ) {
      throw new Error("The OpenAI engine returned a non-completed Tool call.");
    }

    if (functionCalls.length > 0 && !isNonEmptyString(response.id)) {
      throw new Error("The OpenAI engine returned Tool calls without a response ID.");
    }

    for (const call of functionCalls) {
      if (!isNonEmptyString(call.call_id)) {
        throw new Error("The OpenAI engine returned a Tool call without a call ID.");
      }
      if (!isNonEmptyString(call.name)) {
        throw new Error("The OpenAI engine returned a Tool call without a name.");
      }
    }

    const commandText = extractOptionalResponseText(response);

    if (functionCalls.length > 0 && commandText) {
      throw new Error("The OpenAI engine returned both a command and Tool calls.");
    }

    const calls = functionCalls.map((item) => ({
      id: item.call_id,
      name: item.name,
      arguments: parseToolCallArguments(item.arguments)
    }));

    if (calls.length > 0) {
      return {
        type: "tool_calls",
        calls,
        continuation: { responseId: response.id }
      };
    }

    return {
      type: "command",
      ...parseEngineResponse(commandText || extractResponseText(response))
    };
  }

  async #getClient() {
    if (this.client) {
      return this.client;
    }

    if (!this.apiKey) {
      throw new Error("OPENAI_API_KEY is not set. Set it and retry, or use --engine mock.");
    }

    this.clientPromise ??= this.clientFactory({
      apiKey: this.apiKey,
      baseURL: this.baseURL,
      timeoutMs: this.timeoutMs,
      maxRetries: this.maxRetries
    });
    this.client = await this.clientPromise;

    return this.client;
  }
}

export function __testUtils() {
  return {
    buildUserPrompt,
    extractResponseText,
    parseEngineResponse
  };
}
